plugin:
    name: 'shohabbos.paymeshopaholic::lang.plugin.name'
    description: 'shohabbos.paymeshopaholic::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-paypal
    homepage: 'https://itmaker.uz'
